backend:
  name: github
  repo: jeonwon26/jeonwon-center
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "activities"
    label: "활동내용"
    folder: "content/activities"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "요약", name: "excerpt", widget: "string" }
      - { label: "본문", name: "body", widget: "markdown" }
