backend:
  name: github
  repo: jeonwon26/jeonwon-center
  branch: main
  base_url: https://jeonwon-center.vercel.app
  auth_endpoint: api/auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "activities"
    label: "활동내용"
    folder: "content/activities"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime" }
      - { label: "요약", name: "summary", widget: "text", required: false }
      - label: "사진"
        name: "images"
        widget: "list"
        required: false
        field:
          label: "이미지"
          name: "image"
          widget: "image"
      - { label: "본문", name: "body", widget: "markdown" }

  - name: "notices"
    label: "공지사항"
    folder: "content/notices"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" }
